### ISSUE TITLE
Error in mozilla Firefox : Unhandled Promise rejection

### ISSUE THREAD

**Issue by benjibenoit** [Kitsune-tools/ANAChat-Web#2]
Hi,

I'm usign the wordpress plugin for ana-chatbot which work really nice with chrome. When I'm trying to access to my website with firefox, I can't access to the chatbot due to :
`Unhandled Promise rejection: getComputedStyle(...) is null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: "getComputedStyle(...) is null"`

Any ideas ?

Regards,
Shankiflang

**Comment by NizamLZ** [comment]
Thank you for raising the issue. We will look into it immediately. 

Glad to know you are using our WordPress plugin.

**Comment by benjibenoit** [comment]
Any news ?

**Comment by NizamLZ** [comment]
We have released an update of Ana WordPress plugin. Use the latest one and this issue should be resolved

**Comment by benjibenoit** [comment]
I don't see any new versions. I got the 1.0 and Wordpress tell me that it's the latest. However, I still have the error. Have you changed the version number so I can apply an update?

**Comment by NizamLZ** [comment]
Can you delete and install the plugin again, that should give you the updated one. Version number is not updated.

**Comment by benjibenoit** [comment]
धन्यवाद, यह अभी ठीक काम करता है

**Comment by NizamLZ** [comment]
Most welcome!
